---
- hosts: all
  become_user: kotti

  tasks:
  - name: install postgres requirements
    become_user: root
    become: yes
    apt: name=python-psycopg2

  - name: install virtualenv
    become_user: root
    become: yes
    apt: name=python-virtualenv

  - name: install pip
    become_user: root
    become: yes
    apt: name=python-pip

  - name: install supervisord
    become_user: root
    become: yes
    apt: name=supervisor

  - name: create kotti user
    become_user: root
    become: yes
    user: name=kotti home={{workdir}} system=yes

  - name: prepare buildout env
    pip: name=zc.buildout virtualenv={{workdir}}
    become: yes

  - name: copy buildout config
    copy: dest={{workdir}}/buildout.cfg src=resources/kotti.buildout
    become: yes

  - name: run buildout
    command: ./bin/buildout chdir={{workdir}}
    become: yes

  - name: create instance dir
    file: path={{workdir}}/instances state=directory
    become: yes

  - include: instance.yml instance={{instances.test}}
  - include: instance.yml instance={{instances.erdenkinder}}

  - name: restart nginx
    service: name=nginx state=reloaded
    become_user: root
    become: yes
