---
- hosts: all
  become_user: kotti

  tasks:
  - name: install postgres requirements
    become_user: root
    become: yes
    apt: name=python-psycopg2

  - name: create postgres user
    become_user: postgres
    become: yes
    postgresql_user: name=kotti password={{database_password}}

  - name: create postgres database
    become_user: postgres
    become: yes
    postgresql_db: name=kotti encoding='UTF-8' owner=kotti

  - name: install virtualenv
    become_user: root
    become: yes
    apt: name=python-virtualenv

  - name: install pip
    become_user: root
    become: yes
    apt: name=python-pip

  - name: install supervisord
    become_user: root
    become: yes
    apt: name=supervisor

  - name: create kotti user
    become_user: root
    become: yes
    user: name=kotti home={{workdir}} system=yes

  - name: prepare buildout env
    pip: name=zc.buildout virtualenv={{workdir}}
    become: yes

  - name: copy buildout config
    copy: dest={{workdir}}/buildout.cfg src=resources/kotti.buildout
    become: yes

  - name: run buildout
    command: ./bin/buildout chdir={{workdir}}
    become: yes

  - name: configure kotti
    template: dest={{workdir}}/app.ini src=resources/app.ini
    become: yes

  - name: configure supervisord
    template: dest=/etc/supervisor/conf.d/kotti.conf src=resources/kotti.supervisord
    become_user: root
    become: yes

  - name: run kotti under supervisord
    supervisorctl: name=kotti state=restarted
    become_user: root
    become: yes

  - name: configure nginx
    copy: dest=/etc/nginx/sites-enabled/kotti.cfg src=resources/kotti.nginx
    become_user: root
    become: yes

  - name: restart nginx
    service: name=nginx state=reloaded
    become_user: root
    become: yes
