---
- hosts: all

  tasks:
  - name: install mysql requirements
    become_user: root
    become: yes
    apt:
      name: "{{ item }}"
    with_items:
      - libmariadbclient-dev
      - python-mysqldb

  - name: install pillow requirements
    become_user: root
    become: yes
    apt:
      name: "{{ item }}"
    with_items:
      - libjpeg-dev
      - zlib1g-dev

  - name: install virtualenv
    become_user: root
    become: yes
    apt: name=python-virtualenv

  - name: install pip
    become_user: root
    become: yes
    apt: name=python-pip

  - name: install supervisord
    become_user: root
    become: yes
    apt: name=supervisor

  - name: create workdir
    become_user: root
    become: yes
    file: path={{workdir}} state=directory owner={{ansible_user_id}}

  - name: prepare buildout env
    pip: name=zc.buildout virtualenv={{workdir}}

  - name: copy buildout config
    template: dest={{workdir}}/buildout.cfg src=resources/kotti.buildout

  - name: run buildout
    command: ./bin/buildout chdir={{workdir}}

  - name: create kotti user
    become_user: root
    become: yes
    user: name=kotti createhome=no system=yes shell=/usr/sbin/nologin

  - name: create instance dir
    file: path={{workdir}}/instances state=directory

  - include: instance.yml instance={{instances.test}}
  - include: instance.yml instance={{instances.erdenkinder}}
  - include: instance.yml instance={{instances.terminal21}}

  - name: restart nginx
    service: name=nginx state=reloaded
    become_user: root
    become: yes
